<?php
return [
	'section1Arr' => [
		'applicants' => [],
		'owner_vessel' => [],
		'marine_unit' => [],
		'vessel' => [],
		'water_used_im' => [],
		'sanitation' => [],
		'waste_liquid' => [],
		'vessel_engine' => [],
		'solid_waste' => [],
		'branch_payment' => [],
		'upload_doc' => [],
	],
	't1_1' => [
		"name_1_t1" => "",
		"applicant_status_1_t1" => "",
		"nationality_1_t1" => "",
		"id_number_1_t1" => "",
		"passport_number_1_t1" => "",
		"place_of_res_1_t1" => "",
		"actual_place_of_res_1_t1" => "",
		"corrs_add_1_t1" => "",
		"land_with_code_1_t1" => "",
		"land_with_ext_1_t1" => "",
		"fax_with_code_1_t1" => "",
		"fax_with_ext_1_t1" => "",
		"mobile_personal_1_t1" => "",
		"mobile_personal_ext_1_t1" => "",
		"mobile_work_1_t1" => "",
		"mobile_work_ext_1_t1" => "",
		"email_personal_1_t1" => "",
		"email_work_1_t1" => "",
		"website_1_t1" => "",
		"doctype_1_t1" => "",
		"reqtype_1_t1" => "",
		"notes_1_t1" => "",
	],
	't1_2' => [
		"name_2_t1" => "",
		"nationality_2_t1" => "",
		"id_number_2_t1" => "",
		"passport_number_2_t1" => "",
		"place_of_res_2_t1" => "",
		"actual_place_of_res_2_t1" => "",
		"partner_ship_rate_by_carat_2_t1" => "",
		"land_with_code_2_t1" => "",
		"fax_with_code_2_t1" => "",
		"mobile_personal_2_t1" => "",
		"mobile_work_2_t1" => "",
		"email_personal_2_t1" => "",
		"email_work_2_t1" => "",
		"website_2_t1" => "",
		"notes_2_t1" => "",
		"same_as_applicant_2_t1" => "",
		"land_with_ext_2_t1" => "",
		"fax_with_ext_2_t1" => "",
		"mobile_personal_ext_2_t1" => "",
		"mobile_work_ext_2_t1" => ""
	],
	't1_3' => [
		"name_of_unit_owner_3_t1" => "",
		"business_attribute_of_3_t1" => "",
		"entity_type_3_t1" => "",
		"commer_reg_no_3_t1" => "",
		"tax_card_no_3_t1" => "",
		"corrs_add_3_t1" => "",
		"carat_quota_3_t1" => "",
		"telephone_3_t1" => "",
		"fax_with_code_3_t1" => "",
		"mobile_number_p_3_t1" => "",
		"mobile_work_w_3_t1" => "",
		"email_personal_3_t1" => "",
		"email_work_3_t1" => "",
		"website_3_t1" => "",
		"notes_3_t1" => "",
		"telephone_ext_3_t1" => "",
		"fax_with_ext_3_t1" => "",
		"mobile_number_p_ext_3_t1" => "",
		"mobile_work_w_ext_3_t1" => ""
	],
	't1_4' => [
		'maritime_unit_arabic_4_t1' => "",
		'maritime_unit_4_t1' => "",
		'reg_number_4_t1' => "",
		'port_of_reg_4_t1' => "",
		'date_of_reg_4_t1' => "",
		'maritime_license_4_t1' => "",
		'craft_4_t1' => "",
		'number_of_crew_4_t1' => "",
		'total_length_of_unit_4_t1' => "",
		'number_of_passenger_4_t1' => "",
		'construction_type_4_t1' => "",
		'total_weight_of_vessel_4_t1' => "",
		'spec_of_rubber_boat_unit_4_t1' => "",
		'classifi_unit_4_t1' => "",
		'marine_activity_unit_4_t1' => "",
		'unit_area_of_activity_4_t1' => "",
		'getty_marina_4_t1' => "",
		'unit_practice_location_4_t1' => "",
	],
	't1_5' => [
		'water_unit_in_5_t1' => "",
		'tank_capacity_5_t1' => "",
		'daily_consumption_5_t1' => "",
		'number_of_tanks_5_t1' => "",		
	],
	't1_6' => [
		'vessel_drainage_in_6_t1' => "",
		'tank_capacity_6_t1' => "",
		'daily_exchange_rate_6_t1' => "",
		'get_rid_of_drainage_6_t1' => "",		
	],
	't1_7' => [
		'vessel_drainage_in_7_t1' => "",
		'tank_capacity_7_t1' => "",
		'get_rid_of_residues_7_t1' => ""		
	],
	't1_8' => [
		'main_motor_per_unit_8_t1' => "",
		'motor_brand_8_t1' => "",
		'eng_capacity_1_8_t1' => "",		
		'eng_capacity_2_8_t1' => "",		
		'eng_capacity_3_8_t1' => "",		
		'eng_capacity_4_8_t1' => "",		
		'type_of_fuel_used_8_t1' => "",
	],
	't1_9' => [
		'waste_collection_in_9_t1' => "",
		'tank_capacity_9_t1' => "",
		'avg_daily_waste_9_t1' => "",		
		'get_rid_of_solid_9_t1' => "",
	],
	't1_10' => [
		'payment_fees' => "00.00"
	],
	't1_11' => [],

	'section2Arr' => [
		'applicants' => [],
		'owner_data' => [],
		'center_data' => [],
		'branch_payment' => [],
		'upload_doc' => [],
	],
	't2_1' => [
		'name_1_t2' => '',
		'applicant_status_1_t2' => '',
		'nationality_1_t2' => '',
		'id_number_1_t2' => '',
		'passport_number_1_t2' => '',
		'place_of_res_1_t2' => '',
		'actual_place_of_res_1_t2' => '',
		'corrs_add_1_t2' => '',
		'land_with_ext_1_t2' => '',
		'land_with_code_1_t2' => '',
		'fax_with_ext_1_t2' => '',
		'fax_with_ext_1_t2' => '',
		'fax_with_code_1_t2' => '',
		'mobile_personal_ext_1_t2' => '',
		'mobile_personal_1_t2' => '',
		'mobile_work_ext_1_t2' => '',
		"mobile_work_1_t2" => '',
		'email_personal_1_t2' => '',
		'email_work_1_t2' => '',
		'website_1_t2' => '',
		'agency_board_1_t2' => '',
		'doc_office_1_t2' => '',
		'reqtype_1_t2' => '',
		'notes_1_t2' => ''
	],
	't2_2' => [
		'name_2_t2' => '',
		'nick_name_2_t2' => '',
		'nationality_2_t2' => '',
		'id_number_2_t2' => '',
		'passport_number_2_t2' => '',
		'place_of_res_2_t2' => '',
		'land_with_ext_2_t2' => '',
		'land_with_code_2_t2' => '',
		'fax_with_ext_2_t2' => '',
		'fax_with_code_2_t2' => '',
		'mobile_personal_ext_2_t2' => '',
		'mobile_personal_2_t2' => '',
		'mobile_work_2_t2' => '',
		'mobile_work_ext_2_t2' => '',
		'email_personal_2_t2' => '',
		'email_work_2_t2' => '',
		'website_2_t2' => '',
		'same_as_applicant_2_t2' => ''

	],
	't2_3' => [
		'center_name_arabic_3_t2' => '',
		'center_name_english_3_t2' => '',
		'license_number_ministry_of_3_t2' => '',
		'license_number_ministry_of_membership_3_t2' => '',
		'commercial_reg_no_3_t2' => '',
		'tax_card_no_3_t2' => '',
		'address_of_the_center_3_t2' => '',
		'telephone_ext_3_t2' => '',
		'landline_no_3_t2' => '',
		'fax_with_ext_3_t2' => '',
		'fax_no_3_t2' => '',
		'mobile_no1_ext_3_t2' => '',
		'mobile_no1_3_t2' => '',
		'mobile_no2_ext_3_t2' => '',
		'mobile_no2_3_t2' => '',
		'email_3_t2' => '',
		'website_3_t2' => '',
		'marine_activity_authorized_3_t2' => '',
		'unit_area_of_activity_3_t2' => '',
	],
	't2_4' => [
		'payment_fees' => "00.00"
	],
	't2_5' => [],

	'section3Arr' => [
		'applicants' => [],
		'owner_data' => [],
		'center_data' => [],
		'branch_payment' => [],
		'upload_doc' => [],
	],

	't3_1' => [
		'name_1_t3' => '',
		'applicant_status_1_t3' => '',
		'nationality_1_t3' => '',
		'id_number_1_t3' => '',
		'passport_number_1_t3' => '',
		'place_of_res_1_t3' => '',
		'actual_place_of_res_1_t3' => '',
		'corrs_add_1_t3' => '',
		'land_with_ext_1_t3' => '',
		'land_with_code_1_t3' => '',
		'fax_with_ext_1_t3' => '',
		'fax_with_ext_1_t3' => '',
		'fax_with_code_1_t3' => '',
		'mobile_personal_ext_1_t3' => '',
		'mobile_personal_1_t3' => '',
		'mobile_work_ext_1_t3' => '',
		"mobile_work_1_t3" => '',
		'email_personal_1_t3' => '',
		'email_work_1_t3' => '',
		'website_1_t3' => '',
		'agency_board_1_t3' => '',
		'doc_office_1_t3' => '',
		'reqtype_1_t3' => '',
		'notes_1_t3' => ''
	],
	't3_2' => [
		'name_2_t3' => '',
		'nick_name_2_t3' => '',
		'id_number_2_t3' => '',
		'passport_number_2_t3' => '',
		'place_of_res_2_t3' => '',
		'land_with_ext_2_t3' => '',
		'land_with_code_2_t3' => '',
		'fax_with_ext_2_t3' => '',
		'fax_with_code_2_t3' => '',
		'mobile_personal_ext_2_t3' => '',
		'mobile_personal_2_t3' => '',
		'mobile_work_2_t3' => '',
		'mobile_work_ext_2_t3' => '',
		'email_personal_2_t3' => '',
		'email_work_2_t3' => '',
		'website_2_t3' => '',
		'same_as_applicant_2_t3' => ''

	],
	't3_3' => [
		'center_name_arabic_3_t3' => '',
		'center_name_english_3_t3' => '',
		'license_number_ministry_of_3_t3' => '',
		'membership_number_3_t3' => '',
		'commercial_reg_no_3_t3' => '',
		'tax_card_no_3_t3' => '',
		'address_of_the_center_3_t3' => '',
		'land_with_ext_3_t3' => '',
		'landline_no_3_t3' => '',
		'fax_no_ext_3_t3' => '',
		'fax_no_3_t3' => '',
		'mobile_no1_ext_3_t3' => '',
		'mobile_no1_3_t3' => '',
		'mobile_no2_ext_3_t3' => '',
		'mobile_no2_3_t3' => '',
		'email_3_t3' => '',
		'website_3_t3' => '',
		'marine_activity_authorized_3_t3' => '',
		'unit_area_of_activity_3_t3' => '',
	],
	't3_4' => [
		'payment_fees' => "00.00"
	],
	't3_5' => [],

	'section4Arr' => [
		'applicants' => [],
		'owner_data' => [],
		'center_data' => [],
		'branch_payment' => [],
		'upload_doc' => [],
	],

	't4_1' => [
		'name_1_t4' => '',
		'applicant_status_1_t4' => '',
		'nationality_1_t4' => '',
		'id_number_1_t4' => '',
		'passport_number_1_t4' => '',
		'place_of_res_1_t4' => '',
		'actual_place_of_res_1_t4' => '',
		'corrs_add_1_t4' => '',
		'land_with_ext_1_t4' => '',
		'land_with_code_1_t4' => '',
		'mobile_personal_ext_1_t4' => '',
		'mobile_personal_1_t4' => '',
		'mobile_work_ext_1_t4' => '',
		"mobile_work_1_t4" => '',
		'email_personal_1_t4' => '',
		'email_work_1_t4' => '',
		'website_1_t4' => '',
		'agency_board_1_t4' => '',
		'doc_office_1_t4' => '',
		'reqtype_1_t4' => '',
		'notes_1_t4' => ''
	],
	't4_2' => [
		'name_2_t4' => '',
		'nick_name_2_t4' => '',
		'id_number_2_t4' => '',
		'passport_number_2_t4' => '',
		'place_of_res_2_t4' => '',
		'land_with_ext_2_t4' => '',
		'land_with_code_2_t4' => '',
		'fax_with_code_ext_2_t4' => '',
		'fax_with_code_2_t4' => '',
		'mobile_personal_ext_2_t4' => '',
		'mobile_personal_2_t4' => '',
		'mobile_work_ext_2_t4' => '',
		'mobile_work_2_t4' => '',
		'email_personal_2_t4' => '',
		'email_work_2_t4' => '',
		'website_2_t4' => '',
		'same_as_applicant_2_t4' => ''

	],
	't4_3' => [
		'company_name_arabic_3_t4' => '',
		'company_name_english_3_t4' => '',
		'license_number_ministry_of_3_t4' => '',
		'membership_number_3_t4' => '',
		'commercial_reg_no_3_t4' => '',
		'tax_card_no_3_t4' => '',
		'address_of_the_center_3_t4' => '',
		'landline_no_ext_3_t4' => '',
		'landline_no_3_t4' => '',
		'fax_no_ext_3_t4' => '',
		'fax_no_3_t4' => '',
		'mobile_no1_ext_3_t4' => '',
		'mobile_no1_3_t4' => '',
		'mobile_no2_ext_3_t4' => '',
		'mobile_no2_3_t4' => '',
		'email_3_t4' => '',
		'website_3_t4' => '',
		'marine_activity_authorized_3_t4' => '',
		'unit_area_of_activity_3_t4' => '',
	],
	't4_4' => [
		'payment_fees' => "00.00"
	],
	't4_5' => [],

	'section5Arr' => [
		'applicants' => [],
		'owner_data' => [],
		'center_data' => [],
		'branch_payment' => [],
		'upload_doc' => [],
	],

	't5_1' => [
		'name_1_t5' => '',
		'applicant_status_1_t5' => '',
		// 'nationality_1_t4' => '',
		'id_number_1_t5' => '',
		'passport_number_1_t5' => '',
		'place_of_res_1_t5' => '',
		'actual_place_of_res_1_t5' => '',
		'corrs_add_1_t5' => '',
		'land_with_code_ext_1_t5' => '',
		'land_with_code_1_t5' => '',
		'fax_with_code_ext_1_t5' => '',
		'fax_with_code_1_t5' => '',
		'mobile_personal_ext_1_t5' => '',
		'mobile_personal_1_t5' => '',
		'mobile_work_ext_1_t5' => '',
		"mobile_work_1_t5" => '',
		'email_personal_1_t5' => '',
		'email_work_1_t5' => '',
		'website_1_t5' => '',
		'agency_board_1_t5' => '',
		'doc_office_1_t5' => '',
		'reqtype_1_t5' => '',
		'notes_1_t5' => ''
	],
	't5_2' => [
		'name_2_t5' => '',
		'nick_name_2_t5' => '',
		'id_number_2_t5' => '',
		'passport_number_2_t5' => '',
		'place_of_res_2_t5' => '',
		'actual_place_of_res_2_t5' => '',
		'land_with_code_ext_2_t5' => '',
		'land_with_code_2_t5' => '',
		'fax_with_code_ext_2_t5' => '',
		'fax_with_code_2_t5' => '',
		'mobile_personal_ext_2_t5' => '',
		'mobile_personal_2_t5' => '',
		'mobile_work_ext_2_t5' => '',
		'mobile_work_2_t5' => '',
		'email_personal_2_t5' => '',
		'email_work_2_t5' => '',
		'website_2_t5' => '',
		'same_as_applicant_2_t5' => ''

	],
	't5_3' => [
		'entity_name_arabic_3_t5' => '',
		'entity_name_english_3_t5' => '',
		// 'license_number_ministry_of_3_t4' => '',
		'membership_number_3_t5' => '',
		'commercial_reg_no_3_t5' => '',
		// 'tax_card_no_3_t4' => '',
		'address_of_the_entity_3_t5' => '',
		'landline_no_ext_3_t5' => '',
		'landline_no_3_t5' => '',
		'fax_no_3_ext_t5' => '',
		'fax_no_3_t5' => '',
		'mobile_no1_ext_3_t5' => '',
		'mobile_no1_3_t5' => '',
		'mobile_no2_ext_3_t5' => '',
		'mobile_no2_3_t5' => '',
		'email_3_t5' => '',
		'website_3_t5' => '',
		'marine_activity_authorized_3_t5' => '',
		'unit_area_of_activity_3_t5' => '',
	],
	't5_4' => [
		'payment_fees' => "00.00"
	],
	't5_5' => [],

	'section6Arr' => [
		'applicants' => [],
		'owner_data' => [],
		'center_data' => [],
		'branch_payment' => [],
		'upload_doc' => [],
	],

	't6_1' => [
		'name_1_t6' => '',
		'applicant_status_1_t6' => '',
		// 'nationality_1_t4' => '',
		'id_number_1_t6' => '',
		'passport_number_1_t6' => '',
		'place_of_res_1_t6' => '',
		'actual_place_of_res_1_t6' => '',
		'corrs_add_1_t6' => '',
		'land_with_code_ext_1_t6' => '',
		'land_with_code_1_t6' => '',
		'fax_with_code_ext_1_t6' => '',
		'fax_with_code_1_t6' => '',
		'mobile_personal_ext_1_t6' => '',
		'mobile_personal_1_t6' => '',
		'mobile_work_ext_1_t6' => '',
		"mobile_work_1_t6" => '',
		'email_personal_1_t6' => '',
		'email_work_1_t6' => '',
		'website_1_t6' => '',
		'agency_board_1_t6' => '',
		'doc_office_1_t6' => '',
		'reqtype_1_t6' => '',
		'notes_1_t6' => ''
	],
	't6_2' => [
		'name_2_t6' => '',
		'nick_name_2_t6' => '',
		'id_number_2_t6' => '',
		'passport_number_2_t6' => '',
		'place_of_res_2_t6' => '',
		'actual_place_of_res_2_t6' => '',
		'land_with_code_ext_2_t6' => '',
		'land_with_code_2_t6' => '',
		'fax_with_code_ext_2_t6' => '',
		'fax_with_code_2_t6' => '',
		'mobile_personal_ext_2_t6' => '',
		'mobile_personal_2_t6' => '',
		'mobile_work_ext_2_t6' => '',
		'mobile_work_2_t6' => '',
		'email_personal_2_t6' => '',
		'email_work_2_t6' => '',
		'website_2_t6' => '',
		'same_as_applicant_2_t6' => ''

	],
	't6_3' => [
		'entity_name_arabic_3_t6' => '',
		'entity_name_english_3_t6' => '',
		// 'license_number_ministry_of_3_t4' => '',
		'membership_number_3_t6' => '',
		'commercial_reg_no_3_t6' => '',
		// 'tax_card_no_3_t4' => '',
		'address_of_the_entity_3_t6' => '',
		'landline_no_ext_3_t6' => '',
		'landline_no_3_t6' => '',
		'fax_no_ext_3_t6' => '',
		'fax_no_3_t6' => '',
		'mobile_no1_ext_3_t6' => '',
		'mobile_no1_3_t6' => '',
		'mobile_no2_ext_3_t6' => '',
		'mobile_no2_3_t6' => '',
		'email_3_t6' => '',
		'website_3_t6' => '',
		'marine_activity_authorized_3_t6' => '',
		'time_period_3_t6' => '',
		'notes_3_t6' => '',
		'unit_area_of_activity_3_t6' => '',
	],
	't6_4' => [
		'payment_fees' => "00.00"
	],
	't6_5' => [],
];